name: Build SatellaJailed

on:
  workflow_dispatch:
  push:
    branches: [ "emt" ]

jobs:
  build:
    runs-on: macos-15
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'

    - uses: waruhachi/theos-action@v2.4.6
      with:
        theos-src: 'theos/theos'
        theos-branch: 'master'
        sdks-src: 'theos/sdks'
        sdks-branch: 'master'
        libgcuniversal: true
        libgcuniversal-src: 'MrGcGamer/LibGcUniversalDocumentation'
        libgcuniversal-branch: 'master'
        altlist: false
        altlist-src: 'opa334/AltList'
        altlist-branch: 'main'

    - name: Install ios18 patched SDK
      run: |
        curl -L -o iPhoneOS18.0.sdk.zip https://github.com/xybp888/iOS-SDKs/releases/download/iOS18.0-SDKs/iPhoneOS18.0.sdk.zip
        unzip -o -q iPhoneOS18.0.sdk.zip -d /Users/runner/work/SatellaJailed/SatellaJailed/theos/sdks/

    - name: Install Jinx
      run: |
        ln -s /Users/runner/work/SatellaJailed/SatellaJailed/theos /Users/runner/theos
        curl -L -o Jinx_Installer.zip https://github.com/Neoncat-OG/SatellaJailed/releases/download/Jinx/Jinx_Installer.zip
        unzip -o -q Jinx_Installer.zip -d Jinx_Installer
        cd Jinx_Installer/Jinx_Installer
        python3 install_jinx.py

        cd /Users/runner/work/SatellaJailed/SatellaJailed/
        
        curl -L -o Jinx-framework-ios.zip https://github.com/Neoncat-OG/SatellaJailed/releases/download/Jinx/Jinx-framework-ios.zip
        mkdir -p Tweak/Frameworks
        unzip -o -q Jinx-framework-ios.zip -d Tweak/Frameworks/

        curl -L -o Jinx_Sources.zip https://github.com/Neoncat-OG/SatellaJailed/releases/download/Jinx/Jinx_Sources.zip
        mkdir -p Tweak/Sources
        unzip -o -q Jinx_Sources.zip -d Tweak/Sources/
        
        
    - name: Build tweak
      run: |
        make clean package ROOTLESS=0

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: satella-deb
        path: packages/*.deb
